#!/bin/bash

PROGNAME=$(basename "$0")
PID_PATH=$1; shift
COMMAND=$@
WAITPID=
BOOTING=1

log() {
  echo "[${PROGNAME}] $1"
}

log_signal_action() {
  log "Received signal $1, $2 container ..."
  return
}

start_command() {
  log "Starting ..."
  $COMMAND  &
  WAITPID=$!
}

wait_until_stop(){
  pid=$1
  while kill -0 "$pid" 2>/dev/null ; do
    sleep 1
  done
}
pass_trap() {
  pid=$(cat ${PID_PATH})
  if [[ "$pid" == "" ]]; then
    kill -$1 $WAITPID
  else
    kill -$1 $pid
  fi
}

# http://stackoverflow.com/a/2183063/430128
trapsig() {
  func="$1"; shift
  for sig ; do
    trap "$func $sig" "$sig"
  done
}

trapsig pass_trap HUP USR2 USR1 INT TERM QUIT CHLD ALRM PIPE

[ -f $PID_PATH ] && WAITPID=$(cat ${PID_PATH})
if [ "$WAITPID" != "" ] && ( kill -0 "$WAITPID"  2>/dev/null) ; then 
  BOOTING=0
else 
  start_command
fi 

result=0

while [[ $WAITPID != 0 && $WAITPID != "" ]]; do
  if [[ $BOOTING == 1 ]]; then
    wait $WAITPID
  else
    wait_until_stop $WAITPID
  fi
  BOOTING=0
  result=$?
  sleep 1
  if [ -f $PID_PATH ] ; then  
    WAITPID=$(cat ${PID_PATH})
  else 
    WAITPID=0
  fi 
  ! kill -0 "$WAITPID"  2>/dev/null && break
done 

exit $result

